### ISSUE TITLE
Just a suggested reference

### ISSUE THREAD

**Issue by Grossdm** [tvaddonsco/plugin.git.browser#10]
I'm sorry, but I don't know how to communicate other than opening issues.

Anyway, I ran across a project for a GitHub scraper. I thought it might have some helpful information for this project, so here it is:

[nelsonic/github-scaper](https://github.com/nelsonic/github-scraper/blob/master/README.md)

**Comment by tvaddonsco** [comment]
Much appreciated, we'll bookmark it.

By the way our Git Browser doesn't scrape, it uses GitHub's official API, as well as Kodi's API for native addon installation.
