### ISSUE TITLE
git browser is only showing the old & deleted zip files

### ISSUE THREAD

**Issue by emadmahdi** [tvaddonsco/plugin.git.browser#11]
i am using git browser to access the zip files that exists in my github username "emadmahdi" ... but i cannot see my current & latest zip files ... instead it show me old zip files which i already deleted from my github account

**Comment by tvaddonsco** [comment]
Reboot your device and let us know if that changes anything. GitHub caches files on your device, and the cache generally won't clear for a bit without a reboot.

**Comment by emadmahdi** [comment]
i did reboot many times and i still have the same problem !!!

**Comment by tvaddonsco** [comment]
Can you please provide a log of what you're doing?

**Comment by emadmahdi** [comment]
![git browser problem page 1](https://user-images.githubusercontent.com/7454511/47470228-d9ae8f80-d7d2-11e8-8034-4ffb4c6f8453.png)
![git browser problem page 2](https://user-images.githubusercontent.com/7454511/47470229-d9ae8f80-d7d2-11e8-8a5d-fee6501816b5.png)

1.  Enter Git Browser
2.  Enter "Search by GitHub Username"
3.  Enter my own github username "emadmahdi" (as shown in attached photos)
4.  Got the zip files list (as shown in attached photos)
5.  i noticed that only the zip file of "urlresolver" plugin is correct version (may be because it has been added in the last few days)
6.  i tried deleting my username from git browser and enter it again but it did not solve the problem
7.  i tried deleting my whole KODI github repository and created another one with the same name but it did not solve the problem
8.  i tried rebooting my pc many times and it did not fix the problem
9.  i have this problem since september (and since i used git browser for the first time)

**Comment by tvaddonsco** [comment]
It is fixed in the latest update we just pushed, please try again and let us know if all is satisfactory. Thank you!
