### ISSUE TITLE
Git Hub Browser Kodi

### ISSUE THREAD

**Issue by BillySastard** [tvaddonsco/plugin.git.browser#12]

**Comment by BillySastard** [comment]
Ever since installing github browser in kodi I haven't been able to access any TV, Film ect ! I have tried to uninstall  it but cannot find how that is done ! git hub browser has left my  kodi virtually useless !!

**Comment by tvaddonsco** [comment]
It is fixed in the latest update we just pushed, please try again and let us know if all is satisfactory. Thank you!
